Repository Sonny-Trello/trello, pull requests merged in 2024-03, with the labels that each got.

#2 feat/ptj-ticket
  src/main/java/io/superson/trelloproject/domain/common/entity/Timestamped.java
Labels: bug

#4 [FEAT] implement Enum validation annotation
  src/main/java/io/superson/trelloproject/global/util/validator/EnumSubsetOf.java
  src/main/java/io/superson/trelloproject/global/util/validator/EnumSubsetValidator.java
Labels: enhancement

#6 유저 테이블명 지정
  src/main/java/io/superson/trelloproject/domain/user/entity/User.java
Labels: bug

#8 Feat/nhs user
  src/main/java/io/superson/trelloproject/domain/user/controller/UserController.java
  src/main/java/io/superson/trelloproject/domain/user/dto/PasswordUpdateRequestDto.java
  src/main/java/io/superson/trelloproject/domain/user/dto/UserResponseDto.java
  src/main/java/io/superson/trelloproject/domain/user/entity/User.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserJpaRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/user/service/UserService.java
Labels: enhancement

#9 Feat/inyeong status
  docs/images/trello.svg
  src/main/java/io/superson/trelloproject/TrelloProjectApplication.java
  src/main/java/io/superson/trelloproject/domain/board/controller/BoardController.java
  src/main/java/io/superson/trelloproject/domain/board/dto/BoardRequestDto.java
  src/main/java/io/superson/trelloproject/domain/board/entity/Board.java
  src/main/java/io/superson/trelloproject/domain/board/entity/UserBoard.java
  src/main/java/io/superson/trelloproject/domain/board/repository/command/BoardJpaRepository.java
  src/main/java/io/superson/trelloproject/domain/board/repository/command/BoardRepository.java
  src/main/java/io/superson/trelloproject/domain/board/repository/command/BoardRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/board/repository/command/UserBoardRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/BoardQueryRepository.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/BoardQueryRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/board/service/BoardService.java
  src/main/java/io/superson/trelloproject/domain/comment/entity/Comment.java
  src/main/java/io/superson/trelloproject/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/common/dto/ExceptionDto.java
  src/main/java/io/superson/trelloproject/domain/common/dto/ResponseDto.java
  src/main/java/io/superson/trelloproject/domain/common/entity/Timestamped.java
  src/main/java/io/superson/trelloproject/domain/status/controller/StatusController.java
  src/main/java/io/superson/trelloproject/domain/status/dto/CreateStatusResponseDto.java
  src/main/java/io/superson/trelloproject/domain/status/dto/StatusRequestDto.java
  src/main/java/io/superson/trelloproject/domain/status/dto/UpdateStatusResponseDto.java
  src/main/java/io/superson/trelloproject/domain/status/entity/Status.java
  src/main/java/io/superson/trelloproject/domain/status/repository/StatusRepository.java
  src/main/java/io/superson/trelloproject/domain/status/repository/StatusRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/status/service/StatusService.java
  src/main/java/io/superson/trelloproject/domain/ticket/entity/Ticket.java
  src/main/java/io/superson/trelloproject/domain/user/controller/UserController.java
  src/main/java/io/superson/trelloproject/domain/user/dto/SignUpResponseDto.java
  src/main/java/io/superson/trelloproject/domain/user/dto/UserResponseDto.java
  src/main/java/io/superson/trelloproject/domain/user/entity/User.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserJpaRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/user/repository/query/UserQueryRepository.java
  src/main/java/io/superson/trelloproject/global/config/JpaConfig.java
  src/main/java/io/superson/trelloproject/global/config/WebSecurityConfig.java
  src/main/java/io/superson/trelloproject/global/exception/ExceptionController.java
  src/main/java/io/superson/trelloproject/global/exception/UserPermissionException.java
  src/main/java/io/superson/trelloproject/global/filter/AuthorizationFilter.java
  src/main/java/io/superson/trelloproject/global/impl/UserDetailsImpl.java
  src/main/java/io/superson/trelloproject/global/jwt/JwtUtil.java
  src/main/java/io/superson/trelloproject/global/util/validator/EnumSubsetOf.java
  src/main/resources/application.properties
  src/test/java/io/superson/trelloproject/TrelloProjectApplicationTests.java
Labels: bug, enhancement

#11 [FEAT] implement ticket related features
  src/main/java/io/superson/trelloproject/domain/comment/entity/Comment.java
  src/main/java/io/superson/trelloproject/domain/common/dto/ResponseDto.java
  src/main/java/io/superson/trelloproject/domain/status/dto/UpdateStatusResponseDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/controller/TicketController.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketCreateRequestDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketDetailsResponseDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketResponseDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketUpdateRequestDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketUpdateResponseDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/entity/Assignee.java
  src/main/java/io/superson/trelloproject/domain/ticket/entity/AssigneeId.java
  src/main/java/io/superson/trelloproject/domain/ticket/entity/Ticket.java
  src/main/java/io/superson/trelloproject/domain/ticket/mapper/TicketMapper.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketQuerydslJpaRepository.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketQuerydslRepository.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketQuerydslRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketRepository.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/vo/AssigneeVo.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/vo/CommentVo.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/vo/TicketDetailsVo.java
  src/main/java/io/superson/trelloproject/domain/ticket/service/TicketService.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserJpaRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/command/UserRepositoryImpl.java
Labels: enhancement

#12 feat/nhs-user
  src/main/java/io/superson/trelloproject/domain/user/controller/UserController.java
  src/main/java/io/superson/trelloproject/domain/user/dto/UserInviteResponseDto.java
  src/main/java/io/superson/trelloproject/domain/user/repository/query/UserQueryRepository.java
  src/main/java/io/superson/trelloproject/domain/user/repository/query/UserQueryRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/user/service/UserService.java
  src/main/java/io/superson/trelloproject/global/exception/ExceptionController.java
  src/main/java/io/superson/trelloproject/global/exception/UserNotFoundException.java
Labels: enhancement

#15 [Fix] fix issues in ticket domain
  src/main/java/io/superson/trelloproject/domain/ticket/controller/TicketController.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketAssigneeRequestDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketResponseDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketStatusUpdateRequestDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/entity/Assignee.java
  src/main/java/io/superson/trelloproject/domain/ticket/entity/Ticket.java
  src/main/java/io/superson/trelloproject/domain/ticket/mapper/TicketMapper.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketQuerydslRepository.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketQuerydslRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketRepository.java
  src/main/java/io/superson/trelloproject/domain/ticket/repository/TicketRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/ticket/service/TicketService.java
Labels: bug

#14 :sparkles: feat: add get board, status and ticket
  src/main/java/io/superson/trelloproject/domain/board/controller/BoardController.java
  src/main/java/io/superson/trelloproject/domain/board/dto/BoardDetailsResponseDto.java
  src/main/java/io/superson/trelloproject/domain/board/dto/BoardInfoResponseDto.java
  src/main/java/io/superson/trelloproject/domain/board/repository/command/board/BoardRepository.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/BoardQueryRepository.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/BoardQueryRepositoryImpl.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/vo/BoardDetailsVo.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/vo/StatusesVo.java
  src/main/java/io/superson/trelloproject/domain/board/repository/query/vo/TicketsVo.java
  src/main/java/io/superson/trelloproject/domain/board/service/BoardService.java
Labels: enhancement

#16 ✨ feat: Redis를 이용한 BlueLock 적용
  build.gradle
  src/main/java/io/superson/trelloproject/domain/ticket/controller/TicketController.java
  src/main/java/io/superson/trelloproject/domain/ticket/dto/TicketStatusUpdateRequestDto.java
  src/main/java/io/superson/trelloproject/domain/ticket/service/TicketService.java
  src/main/java/io/superson/trelloproject/global/aop/BlueLock.java
  src/main/java/io/superson/trelloproject/global/aop/RedisLock.java
  src/main/resources/application.properties
Labels: enhancement

#17 [DOCS] update readme
  Readme.md
Labels: documentation
